repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.51.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        - --args=--module
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
